### PR TITLE
fix: GO Feature Flag provider fix issues + compatible with SDK 0.1.0

### LINKED ISSUE #128: [Go Feature Flag] null pointer if anonymous not set
We have a null pointer when the field anonymous is not set in the GO Feature Flag provider.

https://github.com/open-feature/java-sdk-contrib/blob/11b5fe74a3400b23571ddd73bef7ca2ec4050dc3/providers/go-feature-flag/src/main/java/dev/openfeature/contrib/providers/gofeatureflag/bean/GoFeatureFlagUser.java#L35-L36

_This issue is here for me to remember to work on it._

### PR DESCRIPTION
**Pull request by thomaspoignant**
## This PR
- Upgrade jackson to fix CVEW-2022-42003.
- Fix NPE when the field `anonymous` is missing.
- Some changes to be compatible with SDK `0.1.0`.

### Related Issues
Fixes #128

### CODE REVIEW

**Review by beeme1mr — APPROVED** [review]
Looks good!

**Comment by beeme1mr** [comment]
@thomaspoignant, in the PR title did you mean to say that it's compatible for SDK v1.0.0?

**Review by toddbaert — APPROVED** [review]
lgtm

**Comment by thomaspoignant** [comment]
> @thomaspoignant, in the PR title did you mean to say that it's compatible for SDK v1.0.0?

This is mostly related to errorCode management.

**Pull request merged**
